### ISSUE TITLE
Features web page does render images

### ISSUE THREAD

**Issue by rdecarreau** [vipm-io/dragon-desktop-issues#2]
On the webpage as of reporting, the images for package-dependencies-ui and -add-package-dependency were not rendering, server replied 404.
https://dragon.vipm.io/features/#adding-package-dependencies

![image](https://github.com/vipm-io/dragon-desktop/assets/31226031/f14e3a1b-9ee6-4010-aa24-c92ac2c1bb6b)

**Comment by jimkring** [comment]
Thanks! It should be fixed now.

**Comment by rdecarreau** [comment]
@jimkring I think that might have broken the landing page buttons, now?
![image](https://github.com/vipm-io/dragon-desktop/assets/31226031/94477698-8f3d-4c33-b7cb-317a21884672)

**Comment by jimkring** [comment]
Yes, thanks. Made some tweaks and broke some stuff :)

Hopefully fixed again soon...
